/**
 * Assembles LOSSY_REPORT.md from per-writer lossy_notes (ROUNDTRIP-05).
 *
 * Three sections — Survived, Approximated, Dropped.
 */

const fs = require('fs');
const path = require('path');

function buildReport({ format, sourcePath, finalPath, regenPath, lossy }) {
  const lines = [
    '# Lossy Roundtrip Report',
    '',
    `**Source format:** \`${format}\``,
    sourcePath ? `**Source path:** \`${sourcePath}\`` : null,
    finalPath ? `**FINAL.md:** \`${finalPath}\`` : null,
    regenPath ? `**Regenerated file:** \`${regenPath}\`` : null,
    '',
    '> tumble-dry roundtrip is **explicitly lossy**. The markdown projection is',
    '> the source of truth for the polished content; the regenerated binary is a',
    '> best-effort re-render. This report tells you exactly what survived, what',
    '> was approximated, and what was dropped on the round trip.',
    '',
    '## Survived',
    '',
  ].filter(l => l !== null);
  for (const item of (lossy.survived || [])) lines.push(`- ${item}`);
  lines.push('', '## Approximated', '');
  for (const item of (lossy.approximated || [])) lines.push(`- ${item}`);
  lines.push('', '## Dropped', '');
  for (const item of (lossy.dropped || [])) lines.push(`- ${item}`);
  lines.push('', '---', '', '_Generated by `lib/writers/lossy-report.cjs` at finalize-with-`--apply` time._', '');
  return lines.join('\n');
}

function writeReport(runDir, payload) {
  const md = buildReport(payload);
  const outPath = path.join(runDir, 'LOSSY_REPORT.md');
  fs.writeFileSync(outPath, md, 'utf-8');
  return outPath;
}

module.exports = { buildReport, writeReport };
